<p>Dear Sir,</p>
<p>Following quotations were prepared today.</p>
<table class='table align-middle table-row-dashed fs-6 gy-5 dataTable no-footer' style='border: 1px solid black;border-collapse: collapse;width:80% !important;min-width:80% !important;'>
<tr>
	<th style='border: 1px solid black;border-collapse: collapse;text-align:left'>ID</th>
	<th style='border: 1px solid black;border-collapse: collapse;text-align:left'>Created On</th>
	<th style='border: 1px solid black;border-collapse: collapse;text-align:left'>Company</th>
	<th style='border: 1px solid black;border-collapse: collapse;text-align:left'>Subject</th>
	<th style='border: 1px solid black;border-collapse: collapse;text-align:left'>Sales Person</th>
	<th style='border: 1px solid black;border-collapse: collapse;text-align:left'>Generated By</th>
	<th style='border: 1px solid black;border-collapse: collapse;text-align:left'>View</th>
</tr>

<?php
//var_dump($quotation_data);die;
if(sizeof($quotation_data)>0)
{
 foreach($quotation_data as $quotation_data){
	$id=$quotation_data->id;
	$addedddttm=$quotation_data->addedddttm;
	$addedddttm = date("d-m-Y", strtotime($addedddttm));
	$comp_name_add=$quotation_data->comp_name_add;
	$subject=$quotation_data->subject;
	$sales_person=$quotation_data->sales_person;

	$sales_person_name="";

	$sales_person_data = DB::select("select * from tbl_user where id='$sales_person'");
	foreach($sales_person_data as $sales_person_data){
		$sales_person_name=$sales_person_data->fullname;
	}

	$addeddby=$quotation_data->addeddby;

	$fullname="";
	if($addeddby=="999999999")
	{
		$fullname="Super Admin";
	}
	else
	{
		$addeddby_data = DB::select("select * from tbl_user where id='$addeddby'");
		foreach($addeddby_data as $addeddby_data){
			$fullname=$addeddby_data->fullname;
		}
	}



	echo "<tr>";
	echo "<td style='border: 1px solid black;border-collapse: collapse'>$id</td>";
	echo "<td style='border: 1px solid black;border-collapse: collapse'>$addedddttm</td>";
	echo "<td style='border: 1px solid black;border-collapse: collapse'>$comp_name_add</td>";
	echo "<td style='border: 1px solid black;border-collapse: collapse'>$subject</td>";
	echo "<td style='border: 1px solid black;border-collapse: collapse'>$sales_person_name</td>";
	echo "<td style='border: 1px solid black;border-collapse: collapse'>$fullname</td>";
	$login_url=url ("/login/$id");
	echo "<td style='border: 1px solid black;border-collapse: collapse'><a href='".$login_url."'>View</a></td>";
	echo "</tr>";

	//echo $fullname;die;

  }
}
else
{
	echo "<tr>";
	echo "<td colspan='6' style='border: 1px solid black;border-collapse: collapse;text-align:center'>No Quotation Available</td>";
	echo "</tr>";
}


  //die;
?>

</table>

<div style="padding-top:15px">NEW PMS ERP</div>
<div style="padding-top:7px">This is a Computer generated email.</div>

<?php
//die;
?>
