<html>
    <head>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    </head>
    <style>
        .invoice{
            color: black !important;
        }
    </style>
<body>
    <div id="invoice">
        <div class="invoice overflow-auto">
            <div style="min-width: 600px">
                <main>
                    <div class="row contacts">
                        <div>Dear Sir/Madam,</div><br>
                        <div>The {{$quotations->count()}} quotation were generated on {{date('M-Y')}}. </div><br>
                    </div><br>
                    <table style='border: 1px solid black;border-collapse: collapse;width:80% !important;min-width:80% !important;' >
                        <thead>
                            <tr>
                                <th style='border: 1px solid black;border-collapse: collapse;text-align:left'>Sr.No.</th>
                                <th style='border: 1px solid black;border-collapse: collapse;text-align:left'>Unique ID</th>
                                <th style='border: 1px solid black;border-collapse: collapse;text-align:left'>Company</th>
                                <th style='border: 1px solid black;border-collapse: collapse;text-align:left'>Subject</th>
                                <th style='border: 1px solid black;border-collapse: collapse;text-align:left'>Sales Person</th>
                                <th style='border: 1px solid black;border-collapse: collapse;text-align:left'>Generated By</th>
                                <th style='border: 1px solid black;border-collapse: collapse;text-align:left'>View </th>
                            </tr>
                        </thead>
                        <tbody>
                            @if ($quotations->count() > 0)
                                @foreach ($quotations as $quotation)
                                    <tr>
                                        @php
                                            $id = $quotation->id ?? 'NA';
                                            $unid= $quotation->unique_id ?? 'NA';
                                            $sales_person = $quotation->getSalesPerson->fullname ?? 'NA';
                                            $company = $quotation->getComanyName->name ?? 'NA';
                                            $generated_by = $quotation->getCreatedBy->fullname ?? 'NA';
                                            $subject = $quotation->subject ?? 'NA';
                                        @endphp
                                        <td style='border: 1px solid black;border-collapse: collapse'>{{ $loop->iteration }}</td>
                                        <td style='border: 1px solid black;border-collapse: collapse'>{{ $unid }}</td>
                                        <td style='border: 1px solid black;border-collapse: collapse'>{{ $company  }}</td>
                                        <td style='border: 1px solid black;border-collapse: collapse'>{{ $subject }}</td>
                                        <td style='border: 1px solid black;border-collapse: collapse'>{{ $sales_person }}</td>
                                        <td style='border: 1px solid black;border-collapse: collapse'>{{ $generated_by }}</td>
                                        <td style='border: 1px solid black;border-collapse: collapse'>
                                            <a target="_blank" href={{route('quotation-master-show',['id' => $id,'action'=> 'with'])}} style="color: #07057b;font-size:20px;" >  &#128206;
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr>
                                        NO Record Found
                                </tr>
                            @endif
                        </tbody>
                    </table><br>
                    <div class="thanks">Thank you!</div>
                    <div class="notices">
                        <div class="notice">For Devharsh Infotech (P) Ltd.</div>
                    </div>
                </main>
            </div>
        </div>
    </div>
</body>
</html>
